import { Course } from "./types";

export const sampleCourses: Course[] = [
  {
    id: "1",
    name: "CSC 110",
    description: "Introduction to Computer Science",
    section: "A02",
    term: "Spring",
    year: 2023,
    professor: "John Doe",
    completed: false,
  },
  {
    id: "2",
    name: "CHEM 150",
    description: "Introduction to Chemistry",
    section: "A01",
    term: "Spring",
    year: 2023,
    professor: "Jane Doe",
    completed: false,
  },
  {
    id: "3",
    name: "MATH 150",
    description: "Introduction to Mathematics",
    section: "A01",
    term: "Spring",
    year: 2023,
    professor: "Mark Smith",
    completed: false,
  },
  {
    id: "4",
    name: "BIO 150",
    description: "Introduction to Biology",
    section: "A01",
    term: "Spring",
    year: 2023,
    professor: "Emma Jones",
    completed: false,
  },
  {
    id: "5",
    name: "GEOG 110",
    description: "Introduction to Geography",
    section: "A02",
    term: "Fall",
    year: 2022,
    professor: "John Doe",
    completed: true,
  },
  {
    id: "6",
    name: "MUSC 110",
    description: "Introduction to Music",
    section: "A01",
    term: "Fall",
    year: 2022,
    professor: "Jane Doe",
    completed: true,
  },
  {
    id: "7",
    name: "PHYS 150",
    description: "Introduction to Physics",
    section: "A01",
    term: "Fall",
    year: 2022,
    professor: "Mark Smith",
    completed: true,
  },
];
