//Note: calendarId is the courseID for the event
export const calendarContent = [
    {
        id: "1",
        calendarId: "1",
        title: "Assignment 1",
        category: "milestone", 
        end: "2023-01-31",
      },
      {
        id: "2",
        calendarId: "1",
        title: "Assignment 2",
        category: "milestone", 
        end: "2023-02-28",
      },
      {
        id: "3",
        calendarId: "1",
        title: "Assignment 3",
        category: "milestone", 
        end: "2023-03-24",
      },
      {
        id: "1",
        calendarId: "2",
        title: "Presentation",
        category: "milestone", 
        end: "2023-02-12",
      },
      {
        id: "2",
        calendarId: "2",
        title: "Assignment 1",
        category: "milestone", 
        end: "2023-03-01",
      },
      {
        id: "4",
        calendarId: "2",
        title: "Project",
        category: "milestone", 
        end: "2023-04-01",
      },
      {
        id: "1",
        calendarId: "3",
        title: "Project",
        category: "milestone", 
        end: "2023-04-09",
      },
      {
        id: "1",
        calendarId: "4",
        title: "Design Project",
        category: "milestone", 
        end: "2023-04-03",
      },
      {
        id: "11",
        calendarId: "1",
        title: "Quiz 1",
        category: "milestone", 
        end: "2023-02-03",
      },
      {
        id: "12",
        calendarId: "1",
        title: "Quiz 2",
        category: "milestone", 
        end: "2023-03-03",
      },
      {
        id: "13",
        calendarId: "1",
        title: "Quiz 3",
        category: "milestone", 
        end: "2023-04-03",
      },
      {
        id: "14",
        calendarId: "2",
        title: "Quiz 1",
        category: "milestone", 
        end: "2023-01-30",
      },
      {
        id: "15",
        calendarId: "2",
        title: "Quiz 2",
        category: "milestone", 
        end: "2023-02-30",
      },
      {
        id: "16",
        calendarId: "2",
        title: "Quiz 3",
        category: "milestone", 
        end: "2023-03-30",
      },
      {
        id: "17",
        calendarId: "3",
        title: "Quiz 1",
        category: "milestone", 
        end: "2023-02-13",
      },
      {
        id: "18",
        calendarId: "3",
        title: "Quiz 2",
        category: "milestone", 
        end: "2023-03-13",
      },
      {
        id: "19",
        calendarId: "3",
        title: "Quiz 3",
        category: "milestone", 
        end: "2023-04-13",
      }
];